{% set name = "spacy-loggers" %}
{% set modulename = "spacy_loggers" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d60b0bdbf915a60e516cc2e653baeff946f0cfc461b452d11a4d5458c6fe5f24

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - {{ modulename }}
  # requires:
  #  - pytest >=5.0.1
  #  - spacy >=3.1
  # commands:
  #  - python -m pytest --tb=native --pyargs {{ modulename }}

about:
  home: https://github.com/explosion/spacy-loggers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate loggers for spaCy pipeline training
  description: Enables alternatives to spaCy's built-in console logger
  doc_url: https://github.com/explosion/spacy-loggers
  dev_url: https://github.com/explosion/spacy-loggers

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - rspeer
    - adrianeboyd
